### PR TITLE
Join match

### PR DESCRIPTION
**Pull request by amr1990**
Join to a private and custom match and leave match

### CODE REVIEW

**Review by bergacat1 — CHANGES_REQUESTED** [review]
For Private matches, you have to check that the Player trying to join the match have an Invitation to join this match. Otherwise, this Player cannot join the match.

Custom matches will have a different way of being joined since in this case the owner of the Custom match have to accept players who want to join it. This feature will be developed by the team in charge of the CustomMatch.

**Comment by amr1990** [comment]
We changed the way that a player joins to a private match by letting him joining it only if he has an invitation to the match. We removed the custom match join test too.

**Review by bergacat1 — CHANGES_REQUESTED** [review]
Even though your tests will never POST a JoinMatch if an Invitation is not created, it is possible to do that through the API. You should block it from the API and try to do it either way to check that the API doesn't allow to do that.

**Comment by amr1990** [comment]
We did the handler that checks if in a player have been invited to a private match, so when a player doesn't have an invite for a private match the api blocks the post request for a JoinMatch.

**Review by bergacat1 — APPROVED** [review]

**Pull request merged**
