### PR TITLE
Schedule match cancelation deadlines

### PR DESCRIPTION
**Pull request by mrg20**
Implemented the last part of cancellation match. Now if a match has a reservation, the reservation is deleted.

### CODE REVIEW

**Review by bergacat1 — CHANGES_REQUESTED** [review]
The reservation should be removed at the time any player leaves a match with a reservation. Otherwise, people could cheat to ensure a reservation for his matches. So it would not be possible that a match reaches the cancelation deadline without sufficient players but with a reservation.

**Comment by mrg20** [comment]
So this isnt a feature about the cancellationdeadline... We will delete this code and create a new handler for that.

**Review by bergacat1 — COMMENTED** [review]
It should be done in the MatchJoinHandler. You can do it even though you are not responsible for MatchJoin features or leave it for the group in charge of that features.

**Comment by mrg20** [comment]
No, We are not going to ""steal"" others work.

**Pull request closed without merging**
