### PR TITLE
Player & MatchResult Entities

### LINKED ISSUE #4: Create/remove player
In order to allow a new player to use the app
As an admin
I want to create a new player account

### PR DESCRIPTION
**Pull request by deinok**
For now, we have created the entities of Player and MatchResult and it's relative configs.

I think that every developer is going to need to reference a Player, so it's better have the file created in order to avoid future merge issues. Specialy in the RepositoryRestConfig.java file.

cc: @poltorres0999 @KeidaS 
Closes #4

### CODE REVIEW

**Comment by bergacat1** [comment]
The task of creating the Player class is being done by another group. Since you mustn't add the relations to other classes now, you don't need to have a Player class. 

Please, only submit a Pull request when your task is completed to the point we have agreed.

**Comment by deinok** [comment]
@bergacat1 Then, we are blocked until #3 and #4 are merged.

**Comment by bergacat1** [comment]
Your task is to create the class MatchResult and test that you can create elements of this type through the REST API. Once you finish this part, you can submit a pull request. After that, you will have to work on the relations of the MatchResult class. Even if #3 and #4 haven't finished, you can temporary create the necessary classes for the relations.

**Comment by bergacat1** [comment]
The Player class is now created at the Master branch

**Comment by deinok** [comment]
Yep, today we will include the players and mark the PR as not WIP

El 5 oct. 2017 15:53, "Albert Berga Gatius" <notifications@github.com>
escribió:

The Player class is now created at the Master branch

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/UdL-EPS-SoftArch/mypadel-api/pull/14#issuecomment-334471767>,
or mute the thread

**Comment by deinok** [comment]
@bergacat1 Hi, should we only test that a MatchResult is created or should we also test the integration with Match and Players?

**Comment by bergacat1** [comment]
For this first PR you should only test the creation of MatchResult. The integration with Match and Players will be the next steps.

**Review by bergacat1 — CHANGES_REQUESTED** [review]
Everything is ok. Just two minor changes before I approve it. 
 - The Player repository is now duplicated (IPlayerRepository and PlayerRepository).
 - In order to follow the same format as other repositories, remove the "I" at the beginning of IMatchResultRepository.

**Comment by deinok** [comment]
@bergacat1 Ready to merge

**Review by bergacat1 — APPROVED** [review]

**Pull request merged**
