### PR TITLE
Event Listeners

### PR DESCRIPTION
**Pull request by deinok**
Event Listeners, as we have talked ;)

### CODE REVIEW

**Comment by rogargon** [comment]
The handlers (Admin and Match handler) are already working properly in the master branch, closing because not necessary

**Comment by deinok** [comment]
@rogargon That way its deprecated.
https://docs.spring.io/spring-data/rest/docs/current/api/org/springframework/data/rest/core/annotation/RepositoryEventHandler.html

**Comment by rogargon** [comment]
What is deprecated is the annotation value, not the annotation approach. As detailed in the documentation (https://docs.spring.io/spring-data/rest/docs/current/reference/html/#events) the alternatives are a global application listener or a per domain class handlers. The latter is favoured to facilitate independent development by the project subteams

**Comment by deinok** [comment]
Before #43 this logic was broken. Notice that this PR is marked as #38 (Before)
Independently I believe that it's better to use a AbstractRepositoryEventListener (abstract class with compiler checkings) than using a reflection approach (@RepositoryEventHandler) that its marked as deprecated and will be deleted in the future.

**Pull request closed without merging**
