### PR TITLE
Create remove court

### PR DESCRIPTION
**Pull request by rarques**

### CODE REVIEW

**Comment by bergacat1** [comment]
When creating a court, you must indicate whether it is indoor or outdoor. You should also do it in the tests.

**Comment by rarques** [comment]
True, we'll implement it.

**Comment by rarques** [comment]
We've finished the feature, please review.

**Comment by bergacat1** [comment]
You have a step ("The court does not exist") without implementation. You must implement it before I can accept the Pull request.

**Comment by rarques** [comment]
Sorry, it was a reminiscence of an older version.

**Pull request merged**
